FROM php:7.3-cli

RUN apt-get update \
    && apt-get install -y --no-install-recommends unzip \
    && rm -rf /var/lib/apt/lists/*

RUN docker-php-ext-install pdo_mysql
RUN pecl install redis-5.3.7 \
    && docker-php-ext-enable redis
RUN docker-php-ext-install bcmath

COPY --from=composer:2.2 /usr/bin/composer /usr/bin/composer

WORKDIR /app
