<?php

return [
    'root_user_id' => (int) env('PERMISSION_ROOT_USER_ID', 31),
    'catalog' => [
        'quotation.profit.view' => [
            'name' => '查看主表盈亏',
            'group' => 'quotation',
            'type' => 'display',
            'depends_on' => [],
            'sensitive' => false,
        ],
        'quotation.extreme.view' => [
            'name' => '查看极端行情',
            'group' => 'quotation',
            'type' => 'page',
            'depends_on' => [],
            'sensitive' => true,
        ],
        'quotation.extreme.config' => [
            'name' => '管理极端行情配置',
            'group' => 'quotation',
            'type' => 'page',
            'depends_on' => ['quotation.extreme.view'],
            'sensitive' => true,
        ],
        'quotation.listing.view' => [
            'name' => '查看新币雷达',
            'group' => 'quotation',
            'type' => 'page',
            'depends_on' => [],
            'sensitive' => true,
        ],
        'users.view' => [
            'name' => '查看用户',
            'group' => 'users',
            'type' => 'page',
            'depends_on' => [],
            'sensitive' => true,
        ],
        'users.create' => [
            'name' => '创建用户',
            'group' => 'users',
            'type' => 'action',
            'depends_on' => ['users.view'],
            'sensitive' => true,
        ],
        'users.edit' => [
            'name' => '编辑用户',
            'group' => 'users',
            'type' => 'action',
            'depends_on' => ['users.view'],
            'sensitive' => true,
        ],
        'users.renew' => [
            'name' => '用户续费',
            'group' => 'users',
            'type' => 'action',
            'depends_on' => ['users.view'],
            'sensitive' => true,
        ],
        'users.force_logout' => [
            'name' => '强制用户下线',
            'group' => 'users',
            'type' => 'action',
            'depends_on' => ['users.view'],
            'sensitive' => true,
        ],
        'settings.market.view' => [
            'name' => '查看行情配置',
            'group' => 'settings',
            'type' => 'page',
            'depends_on' => [],
            'sensitive' => true,
        ],
        'settings.market.update' => [
            'name' => '修改行情配置',
            'group' => 'settings',
            'type' => 'action',
            'depends_on' => ['settings.market.view'],
            'sensitive' => true,
        ],
        'system.logs.view' => [
            'name' => '查看系统日志',
            'group' => 'system',
            'type' => 'page',
            'depends_on' => [],
            'sensitive' => true,
        ],
        'system.server.view' => [
            'name' => '查看服务器管理',
            'group' => 'system',
            'type' => 'page',
            'depends_on' => [],
            'sensitive' => true,
        ],
        'system.server.restart' => [
            'name' => '重启全部行情服务',
            'group' => 'system',
            'type' => 'action',
            'depends_on' => ['system.server.view'],
            'sensitive' => true,
        ],
        'system.platform.restart' => [
            'name' => '重启单个平台服务',
            'group' => 'system',
            'type' => 'action',
            'depends_on' => ['system.server.view'],
            'sensitive' => true,
        ],
        'platform.address.configure' => [
            'name' => '配置平台钱包地址',
            'group' => 'platform',
            'type' => 'action',
            'depends_on' => [],
            'sensitive' => true,
        ],
        'permissions.manage' => [
            'name' => '管理用户权限',
            'group' => 'permissions',
            'type' => 'page',
            'depends_on' => [],
            'sensitive' => true,
        ],
    ],
];
