[program:biance_socket]
process_name=%(program_name)s_%(process_num)02d
command=/www/server/python_manager/versions/3.6.8/bin/python3.6 /www/wwwroot/tool/app/python/biance.py
autostart=true
autorestart=true
user=root
numprocs=1
redirect_stderr=true
stdout_logfile=/www/wwwroot/tool/storage/logs/supervisor/biance_socket.log
stopwaitsecs=3600
priority=999
