[program:depth_consumer]
process_name=%(program_name)s_%(process_num)02d
command=php /www/wwwroot/tool/artisan start_depth_consumer --batch=2000 --update_batch=1000 --levels=5
autostart=true
autorestart=true
user=root
numprocs=24
redirect_stderr=true
stdout_logfile=/www/wwwroot/tool/storage/logs/supervisor/depth_consumer_%(process_num)d.log
stopwaitsecs=3600
priority=970
