[program:kucoin_socket_3]
process_name=%(program_name)s_%(process_num)02d
command=/www/server/python_manager/versions/3.6.8/bin/python3.6 /www/wwwroot/tool/app/python/kucoin/kucoin_3.py
autostart=true
autorestart=true
user=root
numprocs=1
redirect_stderr=true
stdout_logfile=/www/wwwroot/tool/storage/logs/supervisor/kucoin_socket_3.log
stopwaitsecs=3600
priority=1
