[program:depth_update]
process_name=%(program_name)s_%(process_num)02d
command=php /www/wwwroot/tool/artisan update_depth_price 
autostart=true
autorestart=true
stopasgroup=true
killasgroup=true
user=root
numprocs=1
redirect_stderr=true
stdout_logfile=/www/wwwroot/tool/storage/logs/supervisor/depth_update.log
stopwaitsecs=3600
priority=970
