[program:mexc_socket]
process_name=%(program_name)s_%(process_num)02d
directory=/www/wwwroot/go_project/exchange_hub
command=/www/wwwroot/go_project/exchange_hub/bin/mexc
autostart=true
autorestart=true
stopasgroup=true
killasgroup=true
user=root
numprocs=1
redirect_stderr=true
stdout_logfile=/www/wwwroot/tool/storage/logs/supervisor/mexc_socket_%(process_num)d.log
stopwaitsecs=3600
priority=4
