[program:test]
process_name=%(program_name)s_%(process_num)02d
directory=/www/wwwroot/go_project/exchange_hub
command=/www/wwwroot/go_project/exchange_hub/bin/test
autostart=true
autorestart=true
stopasgroup=true
killasgroup=true
user=root
numprocs=1
redirect_stderr=true
stdout_logfile=/www/wwwroot/tool/storage/logs/supervisor/test.log
stopwaitsecs=3600
priority=2
