[program:xt_socket]
process_name=%(program_name)s_%(process_num)02d
directory=/www/wwwroot/go_project/exchange_hub
command=/www/wwwroot/go_project/exchange_hub/bin/xt
autostart=true
autorestart=true
stopasgroup=true
killasgroup=true
user=root
numprocs=1
redirect_stderr=true
stdout_logfile=/www/wwwroot/tool/storage/logs/supervisor/xt_socket.log
stopwaitsecs=3600
priority=21
